# Page Rank y Redes Sociales

In [2]:
import numpy as np

***1. Explicar el fenómeno de “mundo pequeño”, indicando en qué casos se da y cuáles son las características de un grafo en el que se presenta.***

Creo que se refiere al hecho de que si todas las personas pudieran formar una red social, podríamos conectar a cualquier par de personas con tan solo un camino de longitud 6 (dentro del grafo).

***2. Se tiene la siguiente información parcial sobre un grafo dirigido al cual se le ha aplicado PageRank hasta la convergencia:***

• El PageRank de A es 0,15;

• A tiene 2 links: uno hacia C y otro hacia B;

• C recibe solo dos links, uno de los cuales viene de B;

• El PageRank de D es 0,1;

• B recibe un solo link;

• D solo recibe un link que viene de C;

• Desde C solo sale un link.

***¿Cuántos links salen desde B? Justificar detalladamente.***

Tengo que plantear la siguiente ecuación:

$PR_C = \frac{PR_A}{2} + \frac{PR_B}{N}$

Y como el PageRank de C es el mismo de D, pues todo el PageRank de C va hacia D, vemos que:

$PR_D = \frac{PR_A}{2} + \frac{PR_B}{N}$

Y como el PageRank de B es la mitad del PageRank de A llegamos a: 

$PR_D = \frac{PR_A}{2} + \frac{PR_A}{2N}$

Por lo tanto solo falta despejar la ecuación, una vez hacemos esto llegamos a que $N = 3$. 


***3. Dado el siguiente grafo***

***a. Hallar la matriz de transición***

***b. Analizar qué problemas presenta la misma para poder aplicar el modelo de Random Walker, y cómo es
que los mismos se detectan***

|   | A | B   | C   | D   | E   | F   | G |
|---|---|-----|-----|-----|-----|-----|---|
| A | 0 | 1/2 | 0   | 0   | 0   | 0   | 0 |
| B | 0 | 0   | 1   | 1/3 | 0   | 0   | 0 |
| C | 0 | 0   | 0   | 1/3 | 0   | 0   | 0 |
| D | 0 | 1/2 | 0   | 0   | 1/2 | 0   | 0 |
| E | 0 | 0   | 0   | 0   | 0   | 1   | 0 |
| F | 0 | 0   | 0   | 1/3 | 0   | 0   | 0 |
| G | 0 | 0   | 0   | 0   | 1/2 | 0   | 0 |

Los nodos A y G son dead end pues todo el PageRank quedará atrapado ahí.

***4. Una empresa de alquiler de monopatines eléctricos tiene 4 estaciones (A, B, C, D) en donde los usuarios pueden alquilar monopatines. En experimentos iniciales, la empresa pudo determinar con qué frecuencia los usuarios van desde una estación a otra. Dicha información se presenta en la siguiente tabla.***

***A partir de la información anterior, aplicar PageRank para determinar la cantidad de monopatines que se deben asignar a cada estación al comienzo de cada día, considerando que el total de monopatines de la empresa es 100.***

In [3]:
M4 = np.array([[5/20, 10/15, 2/35, 0/25],
               [8/20, 0/15, 5/35, 6/25],
               [3/20, 3/15, 5/35, 15/25],
               [4/20, 2/15, 23/35, 4/25]])
M4

array([[0.25      , 0.66666667, 0.05714286, 0.        ],
       [0.4       , 0.        , 0.14285714, 0.24      ],
       [0.15      , 0.2       , 0.14285714, 0.6       ],
       [0.2       , 0.13333333, 0.65714286, 0.16      ]])

In [4]:
v4 = np.array([1/4, 1/4, 1/4, 1/4])
v4

array([0.25, 0.25, 0.25, 0.25])

In [5]:
for i in range(1,1000):
    v4 = np.dot(M4, v4)
v4 * 100

array([19.65334757, 19.56110113, 29.73734039, 31.0482109 ])

Apliqué pagerank hasta que los valores convergan. Ahora sabemos, en función de eso, cuantos monopatines le tenemos que asignar a cada estación.

***5. Sea el grafo dirigido G cuya lista de aristas es la siguiente: (A B), (B C), (B D), (D E), (E C), (C A), (C D). Se sabe que los valores de PageRank actuales de los nodos son: A = 0,31 B = 0,30 C = 0,08 D = 0,12 E = 0,19.***

***Calcular el valor de PageRank de cada nodo para la siguiente iteración, usando B = 0,8.***


Asumiendo que $B = 0.8$ es $\beta$ entonces armamos la matriz de teletransportación en función de la original y multiplicamos por los PageRanks:

In [6]:
N5 = np.array([[1/5]*5]*5)
N5

array([[0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2],
       [0.2, 0.2, 0.2, 0.2, 0.2]])

In [7]:
M5 = np.array([[0,1,0,0,0],[0,0,0.5,0.5,0],[0.5,0,0,0.5,0],[0,0,0,0,1],[0,0,1,0,0]]).transpose()
M5

array([[0. , 0. , 0.5, 0. , 0. ],
       [1. , 0. , 0. , 0. , 0. ],
       [0. , 0.5, 0. , 0. , 1. ],
       [0. , 0.5, 0.5, 0. , 0. ],
       [0. , 0. , 0. , 1. , 0. ]])

In [8]:
v5 = np.array([0.31, 0.3, 0.08, 0.12, 0.19])
v5

array([0.31, 0.3 , 0.08, 0.12, 0.19])

In [9]:
beta = 0.8
M5_teleport = beta * M5 + (1-beta) * N5
M5_teleport

array([[0.04, 0.04, 0.44, 0.04, 0.04],
       [0.84, 0.04, 0.04, 0.04, 0.04],
       [0.04, 0.44, 0.04, 0.04, 0.84],
       [0.04, 0.44, 0.44, 0.04, 0.04],
       [0.04, 0.04, 0.04, 0.84, 0.04]])

Y vemos la próxima iteración

In [10]:
np.dot(M5_teleport, v5)

array([0.072, 0.288, 0.312, 0.192, 0.136])

***9. Dado el siguiente grafo:***

***a. Mostrar la distribución de grados;***

***b. Indicar cuál es el diámetro de la red;***

***c. Calcular el coeficiente de clustering promedio;***

***d. Comparar dichos valores con los valores característicos de una red social, analizando semejanzas y diferencias***

Distribucion de grados:

```
A -> 4
B -> 2
C -> 2
D -> 3
E -> 3
F -> 3
G -> 3
```

Diametro de la red: 3

El coeficiente de clustering promedio se calcula como:

```
A -> 1/2
B -> 1
C -> 0
D -> 1/3
E -> 1/3
F -> 1/3
G -> 1/3
```

Las redes sociales tienden a seguir la distribucion de power law, donde la cantidad de nodos 
con grado $k$ se calcula mediante $\frac{1}{k}$, pero vemos que nuestro grafo no sigue dicha distribución. Luego el diámetro de de una red social suele ser bajo, siendo del orden de `log10(n)`, 
    pero vemos que $log_{10}(7) \approx 0.8 << 3$ asi que no es como una red social
en este sentido tampoco. Finalmente el coeficiente de clustering promedio para una
red social suele ser bastante alto (cercano a 1) mientras que el nuestro es bajo
(0.35) asi que nuestro grafo no presenta ningun similitud en estos parametros
comparable con la de una red social.

***11. Realizar TopicRank del topic 1 asociado al grafo dado por lo siguiente:***

• ***A pertenece al topic 1 y enlaza con B, C y E;***

• ***B pertenece al topic 1 y enlaza con A y E;***

• ***C pertenece al topic 2 y enlaza con A, C y D;***

• ***D pertenece al topic 1 y enlaza con E;***

• ***E pertenece al topic 2 y no tiene más links.***


***Realizar 3 iteraciones con beta en 0,3 y rankear los resultados. Determinar si puede considerar que los resultados son adecuados y por qué.***


In [47]:
M11 = np.array([[0, 1/3, 1/3, 0, 1/3], [1/2, 0, 0, 0, 1/2],
                [1/3, 0, 1/3, 1/3, 0], [0, 0, 0, 0, 1], [0.2, 0.2, 0.2, 0.2, 0.2]]).transpose()
M11

array([[0.        , 0.5       , 0.33333333, 0.        , 0.2       ],
       [0.33333333, 0.        , 0.        , 0.        , 0.2       ],
       [0.33333333, 0.        , 0.33333333, 0.        , 0.2       ],
       [0.        , 0.        , 0.33333333, 0.        , 0.2       ],
       [0.33333333, 0.5       , 0.        , 1.        , 0.2       ]])

In [48]:
N11 = np.array([[1/3, 1/3, 0 , 1/3, 0], [1/3, 1/3, 0 , 1/3, 0], [1/3, 1/3, 0 , 1/3, 0],
                [1/3, 1/3, 0 , 1/3, 0], [1/3,1/3, 0, 1/3 , 0]]).transpose()
N11

array([[0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [49]:
beta = 0.3
M11_teleport = beta * M11 + (1 - beta)*N11
M11_teleport

array([[0.23333333, 0.38333333, 0.33333333, 0.23333333, 0.29333333],
       [0.33333333, 0.23333333, 0.23333333, 0.23333333, 0.29333333],
       [0.1       , 0.        , 0.1       , 0.        , 0.06      ],
       [0.23333333, 0.23333333, 0.33333333, 0.23333333, 0.29333333],
       [0.1       , 0.15      , 0.        , 0.3       , 0.06      ]])

In [50]:
v11 = np.array([1/5, 1/5, 1/5, 1/5, 1/5])
for i in range(0,3):
    v11 = np.dot(M11_teleport, v11)
v11

array([0.28744187, 0.27127387, 0.04214587, 0.24691387, 0.15222453])

***14. Aplicar PageRank para el siguiente grafo hasta la convergencia, indicando el ranking final de cada nodo (tomar beta en 0,8).***

In [62]:
M14 = np.array([[0,1,0,0,0,0,0], [0,0,1,0,0,0,0], [0,0,0,1,0,0,0], [1/3,0,0,0,0,1/3,1/3], 
                [0,1/2,1/2,0,0,0,0], [0,0,1,0,0,0,0], [1/7,1/7,1/7,1/7,1/7,1/7,1/7]]).transpose()
M14

array([[0.        , 0.        , 0.        , 0.33333333, 0.        ,
        0.        , 0.14285714],
       [1.        , 0.        , 0.        , 0.        , 0.5       ,
        0.        , 0.14285714],
       [0.        , 1.        , 0.        , 0.        , 0.5       ,
        1.        , 0.14285714],
       [0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.14285714],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.14285714],
       [0.        , 0.        , 0.        , 0.33333333, 0.        ,
        0.        , 0.14285714],
       [0.        , 0.        , 0.        , 0.33333333, 0.        ,
        0.        , 0.14285714]])

In [54]:
N14 = np.array([[1/7]*7])
N14.transpose()

array([[0.14285714],
       [0.14285714],
       [0.14285714],
       [0.14285714],
       [0.14285714],
       [0.14285714],
       [0.14285714]])

In [63]:
M14_teleport = beta * M14 + (1 - beta)*N14
M14_teleport

array([[0.02857143, 0.02857143, 0.02857143, 0.2952381 , 0.02857143,
        0.02857143, 0.14285714],
       [0.82857143, 0.02857143, 0.02857143, 0.02857143, 0.42857143,
        0.02857143, 0.14285714],
       [0.02857143, 0.82857143, 0.02857143, 0.02857143, 0.42857143,
        0.82857143, 0.14285714],
       [0.02857143, 0.02857143, 0.82857143, 0.02857143, 0.02857143,
        0.02857143, 0.14285714],
       [0.02857143, 0.02857143, 0.02857143, 0.02857143, 0.02857143,
        0.02857143, 0.14285714],
       [0.02857143, 0.02857143, 0.02857143, 0.2952381 , 0.02857143,
        0.02857143, 0.14285714],
       [0.02857143, 0.02857143, 0.02857143, 0.2952381 , 0.02857143,
        0.02857143, 0.14285714]])

In [56]:
iterar = lambda beta,M,N,v: beta * np.dot(M,v) + (1 - beta) * N

In [64]:
beta = 0.8
v14 = np.array([1/7]*7)
for i in range(0,3):
    v14 = np.dot(M14_teleport, v14)
v14

array([0.11845102, 0.11739886, 0.21532695, 0.2741491 , 0.03777204,
       0.11845102, 0.11845102])

In [65]:
sum(v14)

0.9999999999999998